language: ruby
env:
  RAILS_ENV=test
script:
  - RAILS_ENV=test bundle exec rspec --backtrace
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
