# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c0a3b30bcde05fedec4bd5085b08338d3d0abbb6b2be004e68b91b9df158952628f3fbfcd0a7ffd7c73764f720270806dac802cc01de8ee639cd9225bcc42c5
  yahoo:
    :client_id: <%= ENV['YAHOO_CONSUMER_KEY'] %>
    :client_secret: <%= ENV['YAHOO_CONSUMER_SECRET'] %>
  google_auth:
    :client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    :client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>

test:
  secret_key_base: 0695f0ad15c291f1b9b1b3c3632b6fc11f9f835113a577fef625671119e979e7ee0a8d3be36fff8bf4fbbbb9de0c924ad56584715e05764218324198093d2a94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
